wandb_version: 1

actor_learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 256
temp:
  desc: null
  value: 0.6
algo:
  desc: null
  value: iw
seed:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711937918.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.19
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
