wandb_version: 1

actor_learning_rate:
  desc: null
  value: 1.0e-05
critic_learning_rate:
  desc: null
  value: 1.0e-05
decay_epoch:
  desc: null
  value: 5
lr_decay:
  desc: null
  value: 1.0
algo:
  desc: null
  value: iw
_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711657039.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.0
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
